ENB.Logistics.Mvc/Controllers/OperatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Dynamic;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using ENB.Test.Logistics.Infrastructure;
using ENB.Test.Logistics.Entities;
using ENB.Logistics.Mvc.Models;
using ENB.Test.Logistics.Repositories.EF;
using ENB.Test.Logistics.Entities.Repositories;


namespace ENB.Logistics.Mvc.Controllers
{
    public class OperatorController : Controller
    {
    
        // GET: Operator

        private readonly IOperatorRepository _operatorRepository;
        private readonly IUnitOfWorkFactory _unitOfWorkFactory;
        private readonly IMapper _imapper;
        const int PageSize = 10;

        //public OperatorController()
        //{ }

        /// <summary>
        /// Initializes a new instance of the OperatorController class.
        /// </summary>
        public OperatorController(IOperatorRepository operatorRepository, IUnitOfWorkFactory unitOfWorkFactory, IMapper imapper)
        {
            _operatorRepository = operatorRepository;
            _unitOfWorkFactory = unitOfWorkFactory;
            _imapper = imapper;
        }
        public ActionResult Index(int page = 1, string sort = "Id", string sortDir = "ASC", string search="")
        {
            int totalRecords = _operatorRepository.FindAll().Count();

            ViewBag.search = search;
           

            IQueryable<Operator> allOperator = _operatorRepository.FindAll().Where(o => o.FirstName.Contains(search) 
                                               || o.LastName.Contains(search)).OrderBy(BuildOrderBy(sort, sortDir)).Skip((page * PageSize) - PageSize).Take(PageSize);


           

            var data = _imapper.Map<List<DisplayOperator>>(allOperator);

            var model = new PagerModel<DisplayOperator> { Data = data, PageNumber = page, PageSize = PageSize, TotalRows = totalRecords };
            return View(model);
        }

        private string BuildOrderBy(string sortOn, string sortDirection)
        {
            if (sortOn.ToLower() == "fullname")
            {
                return String.Format("FirstName {0}, LastName {0}", sortDirection);
            }
            return string.Format("{0} {1}", sortOn, sortDirection);
        }

        public ActionResult Details(int id)
        {
            Operator dbOperator = _operatorRepository.FindById(id);

            ViewBag.Message = dbOperator.FullName;
            
            if (dbOperator == null)
            {
                return HttpNotFound();
            }

            var data = _imapper.Map<DisplayOperator>(dbOperator);

            return View(data);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateAndEditOperator createAndEditOperator)
        {
            var errors = ModelState.Values.SelectMany(v => v.Errors);
            if (ModelState.IsValid)
            {
                try
                {
                    using (_unitOfWorkFactory.Create())
                    {
                        Operator dbOperator = new Operator();

                        _imapper.Map(createAndEditOperator, dbOperator);
                        _operatorRepository.Add(dbOperator);
                        return RedirectToAction("Index");
                    }
                }
                catch (ModelValidationException mvex)
                {
                    foreach (var error in mvex.ValidationErrors)
                    {
                        ModelState.AddModelError(error.MemberNames.FirstOrDefault() ?? "", error.ErrorMessage);
                    }
                }
            }
            return View();
        }

        public ActionResult Edit(int id)
        {
            Operator dbOperator = _operatorRepository.FindById(id);
            if (dbOperator == null)
            {
                return HttpNotFound();
            }
            var data = _imapper.Map<CreateAndEditOperator>(dbOperator);

            return View(data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CreateAndEditOperator createAndEditOperator)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    using (_unitOfWorkFactory.Create())
                    {
                        Operator dbOperatorToUpdate = _operatorRepository.FindById(createAndEditOperator.Id);                       
                        _imapper.Map(createAndEditOperator, dbOperatorToUpdate, typeof(CreateAndEditOperator), typeof(Operator));
                        return RedirectToAction("Index");
                    }
                }
                catch (ModelValidationException mvex)
                {
                    foreach (var error in mvex.ValidationErrors)
                    {
                        ModelState.AddModelError(error.MemberNames.FirstOrDefault() ?? "", error.ErrorMessage);
                    }
                }
            }
            return View();
        }

        public ActionResult Delete(int id)
        {
            Operator dbOperator = _operatorRepository.FindById(id);
            if (dbOperator == null)
            {
                return HttpNotFound();
            }
            var data = _imapper.Map<DisplayOperator>(dbOperator);
            return View(data);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            using (_unitOfWorkFactory.Create())
            {
                _operatorRepository.Remove(id);
            }
            return RedirectToAction("Index");
        }
    }

    }

ENB.Logistics.Mvc/Controllers/OrderPickingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using ENB.Test.Logistics.Infrastructure;
using ENB.Test.Logistics.Entities;
using ENB.Logistics.Mvc.Models;
using ENB.Test.Logistics.Repositories.EF;
using ENB.Test.Logistics.Entities.Repositories;

namespace ENB.Logistics.Mvc.Controllers
{
    public class OrderPickingsController : Controller
    {
        private readonly IOperatorRepository _operatorRepository;
        private readonly IUnitOfWorkFactory _unitOfWorkFactory;
        private readonly IMapper _imapper;

        /// <summary>
        /// Initializes a new instance of the OrderPickingsController class.
        /// </summary>
        public OrderPickingsController(IOperatorRepository operatorRepository, IUnitOfWorkFactory unitOfWorkFactory, IMapper imapper)
        {
            _operatorRepository = operatorRepository;
            _unitOfWorkFactory = unitOfWorkFactory;
            _imapper = imapper;
        }

        public ActionResult List(int operatorId)
        {
            ViewBag.OperatorId = operatorId;
            var operatorx = _operatorRepository.FindById(operatorId, x => x.OrderPickings);
            ViewBag.Message = operatorx.FullName;
            var data = new List<DisplayOrderPicking>();
            _imapper.Map(operatorx.OrderPickings, data);
            return View(data);
        }

        public ActionResult Details(int id, int operatorId)
        {
            ViewBag.OperatorId = operatorId;

            var operatorx = _operatorRepository.FindById(operatorId, x => x.OrderPickings);
            ViewBag.Message = operatorx.FullName;
            var data = new DisplayOrderPicking();
            _imapper.Map(operatorx.OrderPickings.Single(x => x.Id == id), data);

            return View(data);
        }

        public ActionResult Create(int OperatorId)
        {
            ViewBag.OperatorId = OperatorId;
            return View();
        }

        [HttpPost]
        public ActionResult Create(CreateAndEditOrderPicking createAndEditOrderPicking, int operatorId)
        {
            ViewBag.OperatorId = operatorId;
            if (ModelState.IsValid)
            {
                try
                {
                    using (_unitOfWorkFactory.Create())
                    {
                        var operatorx = _operatorRepository.FindById(operatorId);
                        var orderpicking = new OrderPicking();

                        ViewBag.Message = operatorx.FullName;

                        _imapper.Map(createAndEditOrderPicking, orderpicking);
                        operatorx.OrderPickings.Add(orderpicking);
                        return RedirectToAction("List", new { operatorId });
                    }
                }
                catch (ModelValidationException mvex)
                {
                    foreach (var error in mvex.ValidationErrors)
                    {
                        ModelState.AddModelError(error.MemberNames.FirstOrDefault() ?? "", error.ErrorMessage);
                    }
                }
            }
            return View();
        }

        public ActionResult Edit(int id, int operatorId)
        {
            ViewBag.OperatorId = operatorId;

            var operatorx = _operatorRepository.FindById(operatorId, x => x.OrderPickings);
            if (operatorx == null)
            {
                return HttpNotFound();
            }
            var data = new CreateAndEditOrderPicking();
            _imapper.Map(operatorx.OrderPickings.Single(x => x.Id == id), data);
            return View(data);
        }

        [HttpPost]
        public ActionResult Edit(CreateAndEditOrderPicking createAndEditOrderPicking, int operatorId)
        {
            ViewBag.OperatorId = operatorId;
            if (ModelState.IsValid)
            {
                try
                {
                    using (_unitOfWorkFactory.Create())
                    {
                        var operatorx = _operatorRepository.FindById(operatorId, x => x.OrderPickings);
                        var orderpicking = operatorx.OrderPickings.Single(x => x.Id == createAndEditOrderPicking.Id);
                        _imapper.Map(createAndEditOrderPicking, orderpicking);
                        return RedirectToAction("List", new { operatorId });
                    }
                }
                catch (ModelValidationException mvex)
                {
                    foreach (var error in mvex.ValidationErrors)
                    {
                        ModelState.AddModelError(error.MemberNames.FirstOrDefault() ?? "", error.ErrorMessage);
                    }
                }
            }
            return View();
        }

        public ActionResult Delete(int id, int operatorId)
        {
            ViewBag.OperatorId = operatorId;

            var operatorx = _operatorRepository.FindById(operatorId, x => x.OrderPickings);
            var data = new DisplayOrderPicking();
            _imapper.Map(operatorx.OrderPickings.Single(x => x.Id == id), data);
            return View(data);
        }

        [HttpPost]
        public ActionResult Delete(DisplayOrderPicking displayOrderPicking, int operatorId)
        {
            ViewBag.OperatorId = operatorId;

            using (_unitOfWorkFactory.Create())
            {
                var operatorx = _operatorRepository.FindById(operatorId, x => x.OrderPickings);
                var orderpicking = operatorx.OrderPickings.Single(x => x.Id == displayOrderPicking.Id);
                operatorx.OrderPickings.Remove(orderpicking);
                return RedirectToAction("List", new { operatorId });
            }
        }

    }
}

ENB.Logistics.Mvc/Controllers/PhoneNumbersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using ENB.Test.Logistics.Infrastructure;
using ENB.Test.Logistics.Entities;
using ENB.Logistics.Mvc.Models;
using ENB.Test.Logistics.Repositories.EF;
using ENB.Test.Logistics.Entities.Repositories;

namespace ENB.Logistics.Mvc.Controllers
{
    public class PhoneNumbersController : Controller
    {
        private readonly IOperatorRepository _operatorRepository;
        private readonly IUnitOfWorkFactory _unitOfWorkFactory;
        private readonly IMapper _imapper;

        /// <summary>
        /// Initializes a new instance of the PhoneNumbersController class.
        /// </summary>
        public PhoneNumbersController(IOperatorRepository operatorRepository, IUnitOfWorkFactory unitOfWorkFactory, IMapper imapper)
        {
            _operatorRepository = operatorRepository;
            _unitOfWorkFactory = unitOfWorkFactory;
            _imapper = imapper;
        }

        public ActionResult List(int operatorId)
        {
            ViewBag.OperatorId = operatorId;
            var operatox = _operatorRepository.FindById(operatorId, x => x.PhoneNumbers);
            ViewBag.Message = operatox.FullName;
            var data = new List<DisplayPhoneNumber>();
            _imapper.Map(operatox.PhoneNumbers, data);
            return View(data);
        }

        public ActionResult Details(int id, int operatorId)
        {
            ViewBag.OperatorId = operatorId;

            var operatorx = _operatorRepository.FindById(operatorId, x => x.PhoneNumbers);
            ViewBag.Message = operatorx.FullName;
            var data = new DisplayPhoneNumber();
            _imapper.Map(operatorx.PhoneNumbers.Single(x => x.Id == id), data);
            return View(data);
        }

        public ActionResult Create(int operatorId)
        {
            ViewBag.OperatorId = operatorId;
            return View();
        }

        [HttpPost]
        public ActionResult Create(CreateAndEditPhoneNumber createAndEditPhoneNumber, int operatorId)
        {
            ViewBag.OperatorId = operatorId;
            if (ModelState.IsValid)
            {
                try
                {
                    using (_unitOfWorkFactory.Create())
                    {
                        var operatorx = _operatorRepository.FindById(operatorId);
                        var phoneNumber = new PhoneNumber();
                        _imapper.Map(createAndEditPhoneNumber, phoneNumber);
                        operatorx.PhoneNumbers.Add(phoneNumber);
                        return RedirectToAction("List", new { operatorId });
                    }
                }
                catch (ModelValidationException mvex)
                {
                    foreach (var error in mvex.ValidationErrors)
                    {
                        ModelState.AddModelError(error.MemberNames.FirstOrDefault() ?? "", error.ErrorMessage);
                    }
                }
            }
            return View();
        }

        public ActionResult Edit(int id, int operatorId)
        {
            ViewBag.OperatorId = operatorId;

            var operatorx = _operatorRepository.FindById(operatorId, x => x.PhoneNumbers);
            if (operatorx == null)
            {
                return HttpNotFound();
            }
            var data = new CreateAndEditPhoneNumber();
            _imapper.Map(operatorx.PhoneNumbers.Single(x => x.Id == id), data);
            return View(data);
        }

        [HttpPost]
        public ActionResult Edit(CreateAndEditPhoneNumber createAndEditPhoneNumber, int operatorId)
        {
            ViewBag.OperatorId = operatorId;
            if (ModelState.IsValid)
            {
                try
                {
                    using (_unitOfWorkFactory.Create())
                    {
                        var operatorx = _operatorRepository.FindById(operatorId, x => x.PhoneNumbers);
                        var phoneNUmber = operatorx.PhoneNumbers.Single(x => x.Id == createAndEditPhoneNumber.Id);
                        _imapper.Map(createAndEditPhoneNumber, phoneNUmber);
                        return RedirectToAction("List", new { operatorId });
                    }
                }
                catch (ModelValidationException mvex)
                {
                    foreach (var error in mvex.ValidationErrors)
                    {
                        ModelState.AddModelError(error.MemberNames.FirstOrDefault() ?? "", error.ErrorMessage);
                    }
                }
            }
            return View();
        }

        public ActionResult Delete(int id, int operatorId)
        {
            ViewBag.OperatorId = operatorId;

            var operatorx = _operatorRepository.FindById(operatorId, x => x.PhoneNumbers);
            var data = new DisplayPhoneNumber();
            _imapper.Map(operatorx.PhoneNumbers.Single(x => x.Id == id), data);
            return View(data);
        }

        [HttpPost]
        public ActionResult Delete(DisplayPhoneNumber displayPhoneNumber, int operatorId)
        {
            ViewBag.OperatorId = operatorId;

            using (_unitOfWorkFactory.Create())
            {
                var operatorx = _operatorRepository.FindById(operatorId, x => x.PhoneNumbers);
                var phoneNumber = operatorx.PhoneNumbers.Single(x => x.Id == displayPhoneNumber.Id);
                operatorx.PhoneNumbers.Remove(phoneNumber);
                return RedirectToAction("List", new { operatorId });
            }
        }

    }

}

ENB.Logistics.Mvc/Views/Operator/Create.cshtml
@model ENB.Logistics.Mvc.Models.CreateAndEditOperator

@{
    ViewBag.Title = "Create";
}

@*<link href="https://ajax.aspnetcdn.com/ajax/jquery.ui/1.10.4/themes/excite-bike/jquery-ui.css" rel="stylesheet" />*@

@section Scripts {

    @Scripts.Render("~/bundles/jqueryui")
        @Styles.Render("~/Content/cssjqryUi")

    

    <script type="text/javascript">

        $(document).ready(function () {
            $('input[type=datetime]').datepicker({
                dateFormat: "dd/M/yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-60:+0",
                buttonText: "Select",
                scrollIinput: false

            });

        });
    </script>

}

<div class="alert alert-dismissible alert-success">
    <h2>Create New Operator</h2>
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OpType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.OpType, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OpType, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
                <input type="button" class="btn btn-success" value="Back to List" onclick="location.href='@Url.Action("Index", "Operator")'" />
            </div>
        </div>
    </div>
}
<br />
<div>


</div>

ENB.Logistics.Mvc/Views/Operator/Delete.cshtml
@model ENB.Logistics.Mvc.Models.DisplayOperator

@{
    ViewBag.Title = "Delete";
}

<br />
    <div class="alert alert-dismissible alert-danger">
        <h2><strong>Are you sure you want to delete this?</strong></h2>
    </div>


<div>       
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateModified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateModified)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OpType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OpType)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
    <br />
<div class="form-actions no-color">
    <input type="submit" value="Delete" class="btn btn-danger" /> |
   
    <input type="button" class="btn btn-success" value="Back to List" onclick="location.href='@Url.Action("Index", "Operator")'" />
</div>
    }
</div>

ENB.Logistics.Mvc/Views/Operator/Details.cshtml
@model ENB.Logistics.Mvc.Models.DisplayOperator
@{
    ViewBag.Title = "Details";
}

    <div class="alert alert-dismissible alert-success">
        <h2><strong> </strong></h2>
        <h2><strong>Details Operator @ViewBag.Message </strong></h2>
    </div>

<div>
    <h4 class="alert-danger">Details Operator @ViewBag.Message</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateModified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateModified)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OpType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OpType)
        </dd>

    </dl>
</div>
<p><br />
   <input type="button" class="btn btn-success" value="Edit" onclick="location.href='@Url.Action("Edit", "Operator", new {id = Model.Id})'" />
    <input type="button" class="btn btn-success" value="Back to List" onclick="location.href='@Url.Action("Index", "Operator")'" />
</p>

ENB.Logistics.Mvc/Views/Operator/Edit.cshtml
@model ENB.Logistics.Mvc.Models.CreateAndEditOperator

@{
    ViewBag.Title = "Edit";
}

<link href="https://ajax.aspnetcdn.com/ajax/jquery.ui/1.10.4/themes/excite-bike/jquery-ui.css" rel="stylesheet" />

@section Scripts {

    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")

    <script type="text/javascript">

     $(document).ready(function () {
         $('input[type=datetime]').datepicker({
             dateFormat: "dd/M/yy",
             changeMonth: true,
             changeYear: true,
             yearRange: "-60:+0",
             buttonText: "Select",
             scrollIinput:false

         });

     });
    </script>

}


<div class="alert alert-dismissible alert-success">
    <h2><strong>Edit operator  @ViewBag.Message</strong></h2>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div class="form-horizontal">             
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OpType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.OpType, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OpType, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
                <input type="button" class="btn btn-success" value="Back to List" onclick="location.href='@Url.Action("Index", "Operator")'" />
            </div>
        </div>
    </div>
}

ENB.Logistics.Mvc/Views/Operator/Index.cshtml
@using ENB.Test.Logistics.Entities;
@model ENB.Logistics.Mvc.Models.PagerModel<ENB.Logistics.Mvc.Models.DisplayOperator>
@{
    ViewBag.Title = "Index";
}

<br />
<div class="alert alert-dismissible alert-success">    
    <h2><strong>Operator Dashboad</strong></h2>
</div>

@if (Model.Data.Any())
{

    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a href="#" class="navbar-brand">Search</a>
            </div>
            <div class="collapse navbar-collapse">
                @using (Html.BeginForm("Index", "Operator", FormMethod.Get, new { @class = "navbar-form navbar-left" }))
                {
                    <div class="form-group">
                        <input type="text" name="search" value="@ViewBag.search" class="form-control" placeholder="search" />
                    </div>
                    <button type="submit" value="Search" class="btn btn-success">Search</button>
                }
            </div>
        </div>
    </nav>




    var grid = new WebGrid(null, defaultSort: "FullName", columnNames: new[] { "Id", "FullName", "DateOfBirth", "Type" }, rowsPerPage: Model.PageSize);
    grid.Bind(Model.Data, rowCount: Model.TotalRows, autoSortAndPage: false);

    <style type="text/css">

        /*Here we will add css for style webgrid*/

        .webgrid-table {
            font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
            font-size: 1.2em;
            width: 100%;
            display: table;
            border-collapse: separate;
            border: solid 1px #98BF21;
            background-color: white;
        }

            .webgrid-table td, th {
                border: 1px solid #98BF21;
                padding: 3px 7px 2px;
            }

        .webgrid-header {
            background-color: #A7C942;
            color: #FFFFFF;
            padding-bottom: 4px;
            padding-top: 5px;
            text-align: left;
        }

        .webgrid-footer {
        }

        .webgrid-row-style {
            padding: 3px 7px 2px;
        }

        .webgrid-alternating-row {
            background-color: #EAF2D3;
            padding: 3px 7px 2px;
        }
    </style>




    @grid.GetHtml(
    htmlAttributes: new
    {
        id = "gridMapping"
    },
    tableStyle: "webgrid-table", //"table table-bordered",
    headerStyle: "webgrid-header",// "info",
    footerStyle: "webgrid-footer",
    alternatingRowStyle: "webgrid-alternating-row",
    selectedRowStyle: "webgrid-selected-row",
    rowStyle: "gridrow",





    columns: grid.Columns(
   grid.Column("Id"),
   grid.Column(header: "Full Name", columnName: "FullName", format: (item) => Html.ActionLink(((string)item.FullName), "Details", new { item.id })),
   grid.Column("DateOfBirth", header: "Date of Birth", format: (item) => item.DateOfBirth.ToString("d")),
   grid.Column("OpType", canSort: false),
   grid.Column(format: (item) => Html.ActionLink("E-addresses", "List", "EmailAddresses", new { operatorId = item.id }, null)),
   grid.Column(format: (item) => Html.ActionLink("Phone", "List", "PhoneNumbers", new { operatorId = item.id }, null)),
   grid.Column(format: (item) => Html.ActionLink("Order Picking", "List", "OrderPickings", new { operatorId = item.id }, null)),
   grid.Column(format: (item) => Html.ActionLink("Edit", "Edit", new { item.id })),
   grid.Column(format: (item) => Html.ActionLink("Delete", "Delete", new { item.id }))
  )
 )
}
else
{
    <p>No Operator found.</p>
}
<br />
<p>
    <input type="button" class="btn btn-success" value="Add new Operator" onclick="location.href='@Url.Action("Create", "Operator")'" />
</p>