ENB.Logistics.Mvc/Models/EmailAddress/CreateAndEditEmailAddress.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using ENB.Test.Logistics.Entities;

namespace ENB.Logistics.Mvc.Models
{
    public class CreateAndEditEmailAddress
    {
        public int Id { get; set; }
        public int OperatorId { get; set; }
        [Required]
        [EmailAddress]
        public string EmailAddressText { get; set; }
        public ProfileType ProfileType { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (ProfileType == ProfileType.None)
            {
                yield return new ValidationResult("ProfileType can't be None.", new[] { "ProfileType" });
            }
        }
    }
}

ENB.Logistics.Mvc/Models/EmailAddress/DisplayEmailAddress.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ENB.Test.Logistics.Entities;

namespace ENB.Logistics.Mvc.Models
{
    public class DisplayEmailAddress
    {
        public int Id { get; set; }
        public int OperatorId { get; set; }
        public string EmailAddressText { get; set; }
        public ProfileType ProfileType { get; set; }
    }
}

ENB.Logistics.Mvc/Controllers/EmailAddressesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using ENB.Test.Logistics.Infrastructure;
using ENB.Test.Logistics.Entities;
using ENB.Logistics.Mvc.Models;
using ENB.Test.Logistics.Repositories.EF;
using ENB.Test.Logistics.Entities.Repositories;


namespace ENB.Logistics.Mvc.Controllers
{
    public class EmailAddressesController : Controller
    {
        private readonly IOperatorRepository _operatorRepository;
        private readonly IUnitOfWorkFactory _unitOfWorkFactory;
        private readonly IMapper _imapper;

        /// <summary>
        /// Initializes a new instance of the EmailAddressesController class.
        /// </summary>
        public EmailAddressesController(IOperatorRepository operatorRepository, IUnitOfWorkFactory unitOfWorkFactory, IMapper iMapper)
        {
            _operatorRepository = operatorRepository;
            _unitOfWorkFactory = unitOfWorkFactory;
            _imapper = iMapper;
        }

        public ActionResult List(int operatorId)
        {
            ViewBag.operatorId = operatorId;
            var operatorx = _operatorRepository.FindById(operatorId, x => x.EmailAddresses);
            ViewBag.Message = operatorx.FullName;
            var data = new List<DisplayEmailAddress>();
            _imapper.Map(operatorx.EmailAddresses, data);
            return View(data);
        }

        public ActionResult Details(int id, int operatorId)
        {
            ViewBag.OperatorId = operatorId;
            var operatorx = _operatorRepository.FindById(operatorId, x => x.EmailAddresses);
            ViewBag.Message = operatorx.FullName;
            var data = new DisplayEmailAddress();
            _imapper.Map(operatorx.EmailAddresses.First(x => x.Id == id), data);
            return View(data);
        }

        public ActionResult Create(int operatorId)
        {
            ViewBag.OperatorId = operatorId;
            return View();
        }

        [HttpPost]
        public ActionResult Create(CreateAndEditEmailAddress createAndEditEmailAddress)
        {
            ViewBag.operatorid = createAndEditEmailAddress.OperatorId;
            if (ModelState.IsValid)
            {
                try
                {
                    using (_unitOfWorkFactory.Create())
                    {
                        var operatorx = _operatorRepository.FindById(createAndEditEmailAddress.OperatorId);
                        var emailAddress = new EmailAddress();
                        _imapper.Map(createAndEditEmailAddress, emailAddress);
                        operatorx.EmailAddresses.Add(emailAddress);
                        return RedirectToAction("List", new { createAndEditEmailAddress.OperatorId });
                    }
                }
                catch (ModelValidationException mvex)
                {
                    foreach (var error in mvex.ValidationErrors)
                    {
                        ModelState.AddModelError(error.MemberNames.FirstOrDefault() ?? "", error.ErrorMessage);
                    }
                }
            }
            return View();
        }

        public ActionResult Edit(int id, int operatorId)
        {
            ViewBag.OperatorId = operatorId;

            var operatorx = _operatorRepository.FindById(operatorId, x => x.EmailAddresses);
            if (operatorx == null)
            {
                return HttpNotFound();
            }
            var data = new CreateAndEditEmailAddress();
            _imapper.Map(operatorx.EmailAddresses.Single(x => x.Id == id), data);
            return View(data);
        }

        [HttpPost]
        public ActionResult Edit(CreateAndEditEmailAddress createAndEditEmailAddress)
        {
            ViewBag.OperatorId = createAndEditEmailAddress.OperatorId;

            if (ModelState.IsValid)
            {
                try
                {
                    using (_unitOfWorkFactory.Create())
                    {
                        var operatorx = _operatorRepository.FindById(createAndEditEmailAddress.OperatorId, x => x.EmailAddresses);
                        var emailAddress = operatorx.EmailAddresses.Single(x => x.Id == createAndEditEmailAddress.Id);
                        _imapper.Map(createAndEditEmailAddress, emailAddress);
                        return RedirectToAction("List", new { createAndEditEmailAddress.OperatorId });
                    }
                }
                catch (ModelValidationException mvex)
                {
                    foreach (var error in mvex.ValidationErrors)
                    {
                        ModelState.AddModelError(error.MemberNames.FirstOrDefault() ?? "", error.ErrorMessage);
                    }
                }
            }
            return View();
        }

        public ActionResult Delete(int id, int operatorId)
        {
            ViewBag.OperatorId = operatorId;
            var operatorx = _operatorRepository.FindById(operatorId, x => x.EmailAddresses);
            if (operatorx == null)
            {
                return HttpNotFound();
            }
            ViewBag.Message = operatorx.FullName;
            var data = new DisplayEmailAddress();
            _imapper.Map(operatorx.EmailAddresses.Single(x => x.Id == id), data);
            return View(data);
        }

        [HttpPost]
        public ActionResult Delete(DisplayEmailAddress displayEmailAddress)
        {
            using (_unitOfWorkFactory.Create())
            {
                var operatorx = _operatorRepository.FindById(displayEmailAddress.OperatorId, x => x.EmailAddresses);
                var address = operatorx.EmailAddresses.Single(x => x.Id == displayEmailAddress.Id);
                operatorx.EmailAddresses.Remove(address);
                return RedirectToAction("List", new { displayEmailAddress.OperatorId });
            }
        }
    }

}

ENB.Logistics.Mvc/Controllers/OperatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Dynamic;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using ENB.Test.Logistics.Infrastructure;
using ENB.Test.Logistics.Entities;
using ENB.Logistics.Mvc.Models;
using ENB.Test.Logistics.Repositories.EF;
using ENB.Test.Logistics.Entities.Repositories;


namespace ENB.Logistics.Mvc.Controllers
{
    public class OperatorController : Controller
    {
    
        // GET: Operator

        private readonly IOperatorRepository _operatorRepository;
        private readonly IUnitOfWorkFactory _unitOfWorkFactory;
        private readonly IMapper _imapper;
        const int PageSize = 10;

        //public OperatorController()
        //{ }

        /// <summary>
        /// Initializes a new instance of the OperatorController class.
        /// </summary>
        public OperatorController(IOperatorRepository operatorRepository, IUnitOfWorkFactory unitOfWorkFactory, IMapper imapper)
        {
            _operatorRepository = operatorRepository;
            _unitOfWorkFactory = unitOfWorkFactory;
            _imapper = imapper;
        }
        public ActionResult Index(int page = 1, string sort = "Id", string sortDir = "ASC", string search="")
        {
            int totalRecords = _operatorRepository.FindAll().Count();

            ViewBag.search = search;
           

            IQueryable<Operator> allOperator = _operatorRepository.FindAll().Where(o => o.FirstName.Contains(search) 
                                               || o.LastName.Contains(search)).OrderBy(BuildOrderBy(sort, sortDir)).Skip((page * PageSize) - PageSize).Take(PageSize);


           

            var data = _imapper.Map<List<DisplayOperator>>(allOperator);

            var model = new PagerModel<DisplayOperator> { Data = data, PageNumber = page, PageSize = PageSize, TotalRows = totalRecords };
            return View(model);
        }

        private string BuildOrderBy(string sortOn, string sortDirection)
        {
            if (sortOn.ToLower() == "fullname")
            {
                return String.Format("FirstName {0}, LastName {0}", sortDirection);
            }
            return string.Format("{0} {1}", sortOn, sortDirection);
        }

        public ActionResult Details(int id)
        {
            Operator dbOperator = _operatorRepository.FindById(id);

            ViewBag.Message = dbOperator.FullName;
            
            if (dbOperator == null)
            {
                return HttpNotFound();
            }

            var data = _imapper.Map<DisplayOperator>(dbOperator);

            return View(data);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateAndEditOperator createAndEditOperator)
        {
            var errors = ModelState.Values.SelectMany(v => v.Errors);
            if (ModelState.IsValid)
            {
                try
                {
                    using (_unitOfWorkFactory.Create())
                    {
                        Operator dbOperator = new Operator();

                        _imapper.Map(createAndEditOperator, dbOperator);
                        _operatorRepository.Add(dbOperator);
                        return RedirectToAction("Index");
                    }
                }
                catch (ModelValidationException mvex)
                {
                    foreach (var error in mvex.ValidationErrors)
                    {
                        ModelState.AddModelError(error.MemberNames.FirstOrDefault() ?? "", error.ErrorMessage);
                    }
                }
            }
            return View();
        }

        public ActionResult Edit(int id)
        {
            Operator dbOperator = _operatorRepository.FindById(id);
            if (dbOperator == null)
            {
                return HttpNotFound();
            }
            var data = _imapper.Map<CreateAndEditOperator>(dbOperator);

            return View(data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CreateAndEditOperator createAndEditOperator)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    using (_unitOfWorkFactory.Create())
                    {
                        Operator dbOperatorToUpdate = _operatorRepository.FindById(createAndEditOperator.Id);                       
                        _imapper.Map(createAndEditOperator, dbOperatorToUpdate, typeof(CreateAndEditOperator), typeof(Operator));
                        return RedirectToAction("Index");
                    }
                }
                catch (ModelValidationException mvex)
                {
                    foreach (var error in mvex.ValidationErrors)
                    {
                        ModelState.AddModelError(error.MemberNames.FirstOrDefault() ?? "", error.ErrorMessage);
                    }
                }
            }
            return View();
        }

        public ActionResult Delete(int id)
        {
            Operator dbOperator = _operatorRepository.FindById(id);
            if (dbOperator == null)
            {
                return HttpNotFound();
            }
            var data = _imapper.Map<DisplayOperator>(dbOperator);
            return View(data);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            using (_unitOfWorkFactory.Create())
            {
                _operatorRepository.Remove(id);
            }
            return RedirectToAction("Index");
        }
    }

    }

ENB.Logistics.Mvc/Views/EmailAddresses/Create.cshtml
@model ENB.Logistics.Mvc.Models.CreateAndEditEmailAddress

@{
    ViewBag.Title = "Create";
}

    <div class="alert alert-dismissible alert-success">
        <h4>Create And Edit EmailAddress</h4>
    </div>

        @using (Html.BeginForm())
        {

            @Html.ValidationSummary(true)
            @Html.Partial("_CreateOrEdit", Model)





            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-success" />
                    <input type="button" class="btn btn-success" value="Back to List" onclick="location.href='@Url.Action("List", "EmailAddresses", new { OperatorId= ViewBag.OperatorId })'" />
                </div>
            </div>








        }

ENB.Logistics.Mvc/Views/EmailAddresses/Delete.cshtml
@model ENB.Logistics.Mvc.Models.DisplayEmailAddress

@{
    ViewBag.Title = "Delete e-mail address?";

}
    <div class="alert alert-dismissible alert-danger">
        <h3>@ViewBag.Title</h3>
    </div>
        <div>
            <hr />
            @Html.Partial("_Details", Model)
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(x => x.OperatorId)

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-danger" /> |
                    <input type="button" class="btn btn-success" value="Cancel" onclick="location.href='@Url.Action("List", "EmailAddresses", new { OperatorId=ViewBag.OperatorId })'" />
                </div>
            }
        </div>

ENB.Logistics.Mvc/Views/EmailAddresses/Details.cshtml
@model ENB.Logistics.Mvc.Models.DisplayEmailAddress


@{
    ViewBag.Title = ViewBag.Message + "Details E=mailAddress";
}
<h2></h2>
<fieldset>
    <legend></legend>
    @Html.Partial("_Details", Model)
</fieldset>



<br /><b>
   
    <input type="button" class="btn btn-success" value="Back to List" onclick="location.href='@Url.Action("List", "EmailAddresses", new {OperatorId = ViewBag.OperatorId })'" />
</b>

ENB.Logistics.Mvc/Views/EmailAddresses/Edit.cshtml
@model ENB.Logistics.Mvc.Models.CreateAndEditEmailAddress

@{
    ViewBag.Title = "Edit An EmaiAddress";
}

    <div class="alert alert-dismissible alert-success">
        <h4>Create And Edit EmailAddress</h4>
    </div>
        <hr />


        @using (Html.BeginForm())
        {
            //  @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            @Html.Partial("_CreateOrEdit", Model)




            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Edit" class="btn btn-success" />
                    <input type="button" class="btn btn-success" value="Back to List" onclick="location.href='@Url.Action("List", "EmailAddresses", new { OperatorId = ViewBag.OperatorId })'" />
                </div>
            </div>


        }

ENB.Logistics.Mvc/Views/EmailAddresses/List.cshtml
@model IEnumerable<ENB.Logistics.Mvc.Models.DisplayEmailAddress>

@{
    ViewBag.Title = ViewBag.Message + " Email-addresses";
}

<style type="text/css">


    .TFtable {
        font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
        font-size: 1.2em;
        display: table;
        width: 100%;
        border-collapse: separate;
        border: solid 1px #4e95f4;
        background-color: white;
    }


        .TFtable th {
            background-color: #A7C942;
        }

        .TFtable th, td {
            padding: 3px 7px 2px;
            border: #98BF21 1px solid;
            text-align: center;
        }
        /* provide some minimal visual accomodation for IE8 and below */
        .TFtable tr {
            background: #EAF2D3;
        }
            /*  Define the background color for all the ODD background rows  */
            .TFtable tr:nth-child(odd) {
                background: #EAF2D3;
            }
            /*  Define the background color for all the EVEN background rows  */
            .TFtable tr:nth-child(even) {
                background: #FFFFFF;
            }
</style>
<hr />
<br />
<div class="alert alert-dismissible alert-success">
    <h2><strong>EmailAddresses  @ViewBag.Message</strong></h2>
</div>
@if (Model.Any())
{
    <table class="TFtable">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.EmailAddressText)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.EmailAddressText)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id, ViewBag.OperatorId }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id, ViewBag.OperatorId }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id, ViewBag.OperatorId })
                </td>
            </tr>
        }

    </table>
    <br />
}
else
{
    < p > No e - mail addresses found.</ p >
}


<p>
    <b>
        <input type="button" class="btn btn-success" value="Create New" onclick="location.href='@Url.Action("Create", "EmailAddresses", new { ViewBag.OperatorId })'" />
        <input type="button" class="btn btn-success" value="Back to start List" onclick="location.href='@Url.Action("Index", "Operator")'" />
    </b>
</p>

ENB.Logistics.Mvc/Views/EmailAddresses/_CreateOrEdit.cshtml
@model ENB.Logistics.Mvc.Models.CreateAndEditEmailAddress


   
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.OperatorId)

        <div class="form-group">
            @Html.LabelFor(model => model.EmailAddressText, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailAddressText, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailAddressText, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProfileType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.ProfileType, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProfileType, "", new { @class = "text-danger" })
            </div>
        </div>

ENB.Logistics.Mvc/Views/EmailAddresses/_Details.cshtml
@model ENB.Logistics.Mvc.Models.DisplayEmailAddress


    <div>
        
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.EmailAddressText)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.EmailAddressText)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ProfileType)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ProfileType)
            </dd>
  </dl>
</div>